### PR TITLE
feat(CHANGELOG): bump up version to 1.1.0

### PR DESCRIPTION
**Pull request by youtalk**
## Description

bump up version to 1.1.0

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by esteve — CHANGES_REQUESTED** [review]
@youtalk please don't tag until this PR is merged (I'm talking about https://github.com/autowarefoundation/autoware_internal_msgs/releases/tag/1.1.0). Tags must point to commits that are in `main` to avoid potential issues with the buildfarm. Remove the tag and recreate when this PR is merged. Thanks.

**Comment by esteve** [comment]
In fact, the tag is already desynchronized with the commit history if this PR is merged because the tag is for a commit that's between https://github.com/autowarefoundation/autoware_internal_msgs/commit/4537a08fdb679bc5f0f1b7fd0f5e54ca5bd3f029 and the current main. I've deleted the tag and we can recreate it when this PR is merged.

**Review by esteve — APPROVED** [review]
Approving now that the tag is removed.

**Comment by esteve** [comment]
@youtalk can you fix the DCO issue? Thanks.

**Comment by youtalk** [comment]
@esteve Thank you for your support. I’ve got it.

**Comment by esteve** [comment]
@youtalk you're welcome 🙂 I've created a tag that points to the current commit in main, we should be able to publish a new package with bloom. Thanks for all the work!

**Pull request merged**
